## IMPORTING PACKAGES

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('diabetess.csv')
X = dataset.iloc[:, :-1].values #get a copy of dataset exclude last column
y = dataset.iloc[:, 1].values #get array of dataset in column 1st

## DATASET

In [3]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

 ## Splitting the dataset into the Training set and Test set


In [4]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

## Fitting Simple Linear Regression to the Training set


In [5]:
X_train

array([[  5.   , 126.   ,  78.   , ...,  29.6  ,   0.439,  40.   ],
       [ 12.   , 100.   ,  84.   , ...,  30.   ,   0.488,  46.   ],
       [  0.   ,  95.   ,  80.   , ...,  36.5  ,   0.33 ,  26.   ],
       ...,
       [  4.   ,  94.   ,  65.   , ...,  24.7  ,   0.148,  21.   ],
       [ 11.   ,  85.   ,  74.   , ...,  30.1  ,   0.3  ,  35.   ],
       [  5.   , 136.   ,  82.   , ...,   0.   ,   0.64 ,  69.   ]])

In [7]:
y_train

array([126, 100,  95, 117,  91,  93,  97, 122, 111,  56, 100, 184, 115,
        78, 114,  68,  85, 119, 136, 125,  80, 121, 137,  75,  85, 169,
       123, 111, 100, 111,  80,  84,  85, 145, 170, 122,  79, 143, 102,
       197, 196,  83,  92, 120, 106, 162, 107, 101, 130, 148, 146, 134,
       130,  80, 144,  84,  92, 142, 114, 125,  83, 140, 194, 125, 122,
       126,  74,  88, 100, 189, 143, 112, 100, 147, 189, 138, 140, 139,
        89,  96, 157,  90, 181,  99, 151, 128, 135, 183, 144,  87, 128,
       118, 184, 180, 133, 142, 124, 120,  81, 145, 135, 131, 108,  89,
       187, 123, 126,  99, 100, 120, 155, 121, 108, 178, 147,  93,  84,
       115,   0, 168, 124,  94,  86, 194, 130,  90, 120, 153, 150, 109,
       151,  95, 163, 101, 102, 111, 179, 112, 187,  84,   0,  95, 141,
       123, 129, 148,  96, 166, 180, 120, 120,  90, 104, 130, 132, 167,
       149, 166,  91, 100, 113, 188, 117, 105, 125, 150, 173,  96, 122,
       132, 106, 181, 114,  88, 101, 187,  93, 125, 158,  86, 12

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

## Prediction

In [10]:
y_pred = model.predict(X_test)
y_pred

array([ 1.99000000e+02,  1.07000000e+02,  7.60000000e+01,  1.66000000e+02,
        1.11000000e+02,  8.10000000e+01,  1.52000000e+02,  1.76000000e+02,
        1.27000000e+02,  1.03000000e+02,  1.58000000e+02,  1.87000000e+02,
        1.14000000e+02,  8.20000000e+01,  6.50000000e+01,  1.08000000e+02,
        1.79000000e+02,  7.30000000e+01,  1.32000000e+02,  9.90000000e+01,
        1.44000000e+02,  1.18000000e+02,  8.70000000e+01,  6.10000000e+01,
        9.70000000e+01,  1.24000000e+02,  1.04000000e+02,  1.53000000e+02,
        1.12000000e+02,  1.10000000e+02,  1.36000000e+02,  1.02000000e+02,
        1.02000000e+02,  1.22000000e+02,  1.19000000e+02,  1.68000000e+02,
        1.36000000e+02,  1.17000000e+02,  1.19000000e+02,  1.80000000e+02,
        1.19000000e+02,  9.00000000e+01,  9.90000000e+01,  1.93000000e+02,
        1.97000000e+02,  1.02000000e+02,  1.08000000e+02,  1.29000000e+02,
        1.09000000e+02,  1.25000000e+02,  1.33000000e+02,  1.08000000e+02,
        1.51000000e+02,  

## Accuracy 

In [11]:
print(model.score(X_test, y_test))

1.0


## Performance  Evaluation
from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('R squared: {:.2f}'.format(regressor.score(X,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

### R Squared: 
        R Square is the coefficient of determination. It tells us how many points fall on the regression line. The value of R Square indicates how the data fit the regression model.
        
        
### Mean Absolute Error: 
         Mean Absolute Error is the absolute difference between the actual or true values and the predicted values. The lower the value, the better is the model’s performance.

### Mean Square Error: 
          Mean Square Error is calculated by taking the average of the square of the difference between the original and predicted values of the data. The lower the value, the better is the model’s performance. 

### Root Mean Square Error: 
          Root Mean Square Error is the standard deviation of the errors which occur when a prediction is made on a dataset. This is the same as Mean Squared Error, but the root of the value is considered while determining the accuracy of the model. The lower the value, the better is the model’s performance.


### Conclusion
         The Multiple Linear Regression model performs well as 95.65% of the data fit the regression model. Also, the mean absolute error, mean square error, and the root mean square error are less